[pytest]
testpaths = .
python_files = test*.py
python_functions = test*
addopts = -vv -s -ra --showlocals
markers =
    requiresOsi: requires FMT compiled with OSI
    requiresMosek: requires FMT compiled with Mosek
    requiresGdal: requires FMT compiled with GDAL
