#[[
Copyright (c) 2019 Gouvernement du Québec

SPDX-License-Identifier: LiLiQ-R-1.1
License-Filename: LICENSES/EN/LiLiQ-R11unicode.txt
]]

# Compares the benchmark results of two sets of runs, written by FMTPerformanceTests (JSON schema
# versions 1 to 4, described in Documentation/PerformanceTesting.md):
#
#   cmake -DBASELINE=<runs> -DCANDIDATE=<runs> -P Tests/Performance/CompareResults.cmake
#
# Each side is one run, or several separated by semicolons. A run is a .json file, or a folder that
# stands for every .json file it holds, such as build/release/tests/performance after a run of ctest.
# For each benchmark, the report gives the change of the median duration, of each phase and of the
# process peak memory in percent, and the allocations and bytes of a typical call before and after.
# With several runs on a side, it compares the middle values of the runs, gives the range of their
# median durations, and says when every candidate run lies outside that range of the baseline. It
# warns when the files of a dataset differ. It only reports: nothing fails on a change.

cmake_minimum_required(VERSION 3.19)

include("${CMAKE_CURRENT_LIST_DIR}/ResultsFormat.cmake")

# Reads the results of p_path, a file or a folder, into variables named
# <p_side>.<benchmark>.<field>, the benchmark names into <p_side>.benchmarks and a description of the
# run into <p_side>.environment. The environment is the one of the first file.
function(_readResults p_path p_side)
	if (IS_DIRECTORY "${p_path}")
		file(GLOB files "${p_path}/*.json")
	else()
		set(files "${p_path}")
	endif()
	if (NOT files)
		message(FATAL_ERROR "No results in ${p_path}")
	endif()
	set(benchmarks "")
	foreach(file IN LISTS files)
		file(READ "${file}" json)
		if (NOT DEFINED environment)
			foreach(field commit dirty buildType cpu mode timestamp)
				string(JSON ${field} GET "${json}" environment ${field})
			endforeach()
			# Results written before the allocator was recorded have none.
			string(JSON allocator ERROR_VARIABLE missingAllocator GET "${json}" environment allocator)
			if (missingAllocator)
				set(allocator "allocator unknown")
			endif()
			# Nor the processors their measuring thread ran on.
			string(JSON processors ERROR_VARIABLE missingProcessors GET "${json}" environment processors)
			if (missingProcessors)
				set(processors "processors unknown")
			endif()
			set(environment "commit ${commit}")
			if (dirty)
				string(APPEND environment " (modified)")
			endif()
			string(APPEND environment ", ${buildType}, ${allocator}, ${cpu} (${processors}), mode ${mode}, ${timestamp}")
			set("${p_side}.cpu" "${cpu}" PARENT_SCOPE)
			set("${p_side}.mode" "${mode}" PARENT_SCOPE)
			set("${p_side}.buildType" "${buildType}" PARENT_SCOPE)
			set("${p_side}.allocator" "${allocator}" PARENT_SCOPE)
			set("${p_side}.processors" "${processors}" PARENT_SCOPE)
		endif()
		string(JSON count LENGTH "${json}" results)
		if (count GREATER 0)
			math(EXPR last "${count} - 1")
			foreach(index RANGE ${last})
				string(JSON name GET "${json}" results ${index} benchmark)
				foreach(field medianNs allocationsPerCallMedian allocatedBytesPerCallMedian processPeakPrivateBytes valid)
					string(JSON value GET "${json}" results ${index} ${field})
					set("${p_side}.${name}.${field}" "${value}" PARENT_SCOPE)
				endforeach()
				# Schema 1 results do not record the memory a call keeps.
				string(JSON value ERROR_VARIABLE missingField GET "${json}" results ${index} retainedBytesPerCallMedian)
				if (missingField)
					set(value "n/a")
				endif()
				set("${p_side}.${name}.retainedBytesPerCallMedian" "${value}" PARENT_SCOPE)
				# Schema 3 adds the fingerprint of the dataset and the phases of a call.
				string(JSON value ERROR_VARIABLE missingField GET "${json}" results ${index} datasetFingerprint)
				if (missingField)
					set(value "")
				endif()
				set("${p_side}.${name}.datasetFingerprint" "${value}" PARENT_SCOPE)
				set(phaseNames "")
				string(JSON phaseCount ERROR_VARIABLE missingField LENGTH "${json}" results ${index} phases)
				if (NOT missingField AND phaseCount GREATER 0)
					math(EXPR lastPhase "${phaseCount} - 1")
					foreach(phaseIndex RANGE ${lastPhase})
						string(JSON phaseName GET "${json}" results ${index} phases ${phaseIndex} name)
						string(JSON phaseMedian GET "${json}" results ${index} phases ${phaseIndex} medianNs)
						list(APPEND phaseNames "${phaseName}")
						set("${p_side}.${name}.phase.${phaseName}" "${phaseMedian}" PARENT_SCOPE)
					endforeach()
				endif()
				set("${p_side}.${name}.phases" "${phaseNames}" PARENT_SCOPE)
				list(APPEND benchmarks "${name}")
			endforeach()
		endif()
	endforeach()
	set("${p_side}.benchmarks" "${benchmarks}" PARENT_SCOPE)
	set("${p_side}.environment" "${environment}" PARENT_SCOPE)
endfunction()

# Writes the middle value of p_values, a list of decimals, into p_result, and their minimum and
# maximum into p_result.min and p_result.max: the median of the values, the mean of the two middle
# ones for an even count. Anything that is not a decimal is left out; with none, all three are empty.
function(_middle p_values p_result)
	set(thousandths "")
	foreach(value IN LISTS p_values)
		_toThousandths("${value}" converted)
		if (NOT converted STREQUAL "")
			list(APPEND thousandths "${converted}")
		endif()
	endforeach()
	list(LENGTH thousandths count)
	if (count EQUAL 0)
		set(${p_result} "" PARENT_SCOPE)
		set(${p_result}.min "" PARENT_SCOPE)
		set(${p_result}.max "" PARENT_SCOPE)
		return()
	endif()
	# A numeric sort: COMPARE NATURAL puts 9 before 10, and no value here is negative but retained
	# bytes, which are never averaged.
	list(SORT thousandths COMPARE NATURAL)
	list(GET thousandths 0 minimum)
	list(GET thousandths -1 maximum)
	math(EXPR half "${count} / 2")
	list(GET thousandths ${half} upper)
	math(EXPR odd "${count} % 2")
	if (odd)
		set(middle "${upper}")
	else()
		math(EXPR lowerIndex "${half} - 1")
		list(GET thousandths ${lowerIndex} lower)
		math(EXPR middle "(${lower} + ${upper}) / 2")
	endif()
	_fromThousandths("${middle}" middle)
	_fromThousandths("${minimum}" minimum)
	_fromThousandths("${maximum}" maximum)
	set(${p_result} "${middle}" PARENT_SCOPE)
	set(${p_result}.min "${minimum}" PARENT_SCOPE)
	set(${p_result}.max "${maximum}" PARENT_SCOPE)
endfunction()

# Writes the values of p_values, whole numbers or text, as one value when they are all equal, or as
# "<lowest>..<highest>" when they are whole numbers that differ.
function(_valueOrRange p_values p_result)
	list(REMOVE_DUPLICATES p_values)
	list(LENGTH p_values count)
	if (count LESS 2)
		set(${p_result} "${p_values}" PARENT_SCOPE)
		return()
	endif()
	list(GET p_values 0 lowest)
	set(highest "${lowest}")
	foreach(value IN LISTS p_values)
		if (NOT value MATCHES "^-?[0-9]+$")
			string(REPLACE ";" ", " values "${p_values}")
			set(${p_result} "${values}" PARENT_SCOPE)
			return()
		endif()
		if (value LESS lowest)
			set(lowest "${value}")
		endif()
		if (value GREATER highest)
			set(highest "${value}")
		endif()
	endforeach()
	set(${p_result} "${lowest}..${highest}" PARENT_SCOPE)
endfunction()

# Combines the runs of p_side into <p_side>.<benchmark>.<field>, for every benchmark of any of its
# runs: the middle median duration, phase and peak memory with the range of the median durations,
# the allocations and bytes of a typical call as one value or a range, valid only if every run is.
function(_combineRuns p_side)
	set(benchmarks "")
	foreach(run RANGE 1 ${${p_side}.runs})
		list(APPEND benchmarks ${${p_side}.${run}.benchmarks})
	endforeach()
	list(REMOVE_DUPLICATES benchmarks)
	foreach(name IN LISTS benchmarks)
		set(runs "")
		set(medians "")
		set(peaks "")
		set(phases "")
		set(fingerprint "")
		set(valid ON)
		foreach(field allocationsPerCallMedian allocatedBytesPerCallMedian retainedBytesPerCallMedian)
			set(${field} "")
		endforeach()
		foreach(run RANGE 1 ${${p_side}.runs})
			set(prefix "${p_side}.${run}.${name}")
			if (NOT DEFINED ${prefix}.medianNs)
				continue()
			endif()
			list(APPEND runs ${run})
			list(APPEND medians "${${prefix}.medianNs}")
			list(APPEND peaks "${${prefix}.processPeakPrivateBytes}")
			foreach(field allocationsPerCallMedian allocatedBytesPerCallMedian retainedBytesPerCallMedian)
				list(APPEND ${field} "${${prefix}.${field}}")
			endforeach()
			if (NOT ${prefix}.valid)
				set(valid OFF)
			endif()
			if (fingerprint STREQUAL "")
				set(fingerprint "${${prefix}.datasetFingerprint}")
			elseif (NOT "${${prefix}.datasetFingerprint}" STREQUAL "" AND NOT "${${prefix}.datasetFingerprint}" STREQUAL fingerprint)
				set(fingerprint "differs")
			endif()
			foreach(phase IN LISTS ${prefix}.phases)
				if (NOT phase IN_LIST phases)
					list(APPEND phases "${phase}")
				endif()
				list(APPEND "phase.${name}.${phase}" "${${prefix}.phase.${phase}}")
			endforeach()
		endforeach()
		set(out "${p_side}.${name}")
		list(LENGTH runs runCount)
		set(${out}.runCount "${runCount}" PARENT_SCOPE)
		_middle("${medians}" median)
		set(${out}.medianNs "${median}" PARENT_SCOPE)
		set(${out}.medianNs.min "${median.min}" PARENT_SCOPE)
		set(${out}.medianNs.max "${median.max}" PARENT_SCOPE)
		_middle("${peaks}" peak)
		set(${out}.processPeakPrivateBytes "${peak}" PARENT_SCOPE)
		foreach(field allocationsPerCallMedian allocatedBytesPerCallMedian retainedBytesPerCallMedian)
			_valueOrRange("${${field}}" value)
			set(${out}.${field} "${value}" PARENT_SCOPE)
		endforeach()
		set(${out}.valid "${valid}" PARENT_SCOPE)
		set(${out}.datasetFingerprint "${fingerprint}" PARENT_SCOPE)
		set(${out}.phases "${phases}" PARENT_SCOPE)
		foreach(phase IN LISTS phases)
			_middle("${phase.${name}.${phase}}" phaseMedian)
			set(${out}.phase.${phase} "${phaseMedian}" PARENT_SCOPE)
		endforeach()
	endforeach()
	set(${p_side}.benchmarks "${benchmarks}" PARENT_SCOPE)
endfunction()

# Prints what changed for one benchmark present on both sides.
function(_reportBenchmark p_name)
	set(before "baseline.${p_name}")
	set(after "candidate.${p_name}")
	_percentChange("${${before}.medianNs}" "${${after}.medianNs}" durationChange)
	_percentChange("${${before}.processPeakPrivateBytes}" "${${after}.processPeakPrivateBytes}" memoryChange)
	_formatDuration("${${before}.medianNs}" durationBefore)
	_formatDuration("${${after}.medianNs}" durationAfter)
	message("${p_name}")
	if ("${${before}.datasetFingerprint}" STREQUAL "differs" OR "${${after}.datasetFingerprint}" STREQUAL "differs")
		message("  WARNING: the files of the dataset differ between the runs of a side, the results do not compare")
	elseif (NOT "${${before}.datasetFingerprint}" STREQUAL "" AND NOT "${${after}.datasetFingerprint}" STREQUAL ""
		AND NOT "${${before}.datasetFingerprint}" STREQUAL "${${after}.datasetFingerprint}")
		message("  WARNING: the files of the dataset differ, the results do not compare")
	endif()
	set(spread "")
	if (${before}.runCount GREATER 1 OR ${after}.runCount GREATER 1)
		_formatDuration("${${before}.medianNs.min}" beforeMin)
		_formatDuration("${${before}.medianNs.max}" beforeMax)
		_formatDuration("${${after}.medianNs.min}" afterMin)
		_formatDuration("${${after}.medianNs.max}" afterMax)
		set(spread ", runs ${beforeMin}..${beforeMax} -> ${afterMin}..${afterMax}")
		if (${before}.runCount GREATER 1)
			_toThousandths("${${before}.medianNs.min}" lowestBefore)
			_toThousandths("${${before}.medianNs.max}" highestBefore)
			_toThousandths("${${after}.medianNs.min}" lowestAfter)
			_toThousandths("${${after}.medianNs.max}" highestAfter)
			if (highestAfter LESS lowestBefore)
				string(APPEND spread ", below every baseline run")
			elseif (lowestAfter GREATER highestBefore)
				string(APPEND spread ", above every baseline run")
			endif()
		endif()
	endif()
	message("  Median duration:  ${durationChange}  (${durationBefore} -> ${durationAfter})${spread}")
	foreach(phase IN LISTS ${after}.phases)
		if (phase IN_LIST ${before}.phases)
			_percentChange("${${before}.phase.${phase}}" "${${after}.phase.${phase}}" phaseChange)
			_formatDuration("${${before}.phase.${phase}}" phaseBefore)
			_formatDuration("${${after}.phase.${phase}}" phaseAfter)
			message("    ${phase}:  ${phaseChange}  (${phaseBefore} -> ${phaseAfter})")
		endif()
	endforeach()
	message("  Allocations:      ${${before}.allocationsPerCallMedian} -> ${${after}.allocationsPerCallMedian} per call")
	message("  Allocated bytes:  ${${before}.allocatedBytesPerCallMedian} -> ${${after}.allocatedBytesPerCallMedian} per call")
	message("  Retained bytes:   ${${before}.retainedBytesPerCallMedian} -> ${${after}.retainedBytesPerCallMedian} per call")
	message("  Peak memory:      ${memoryChange}  (process peak private bytes)")
	if (NOT ${before}.valid)
		message("  INVALID in the baseline: its checks failed")
	endif()
	if (NOT ${after}.valid)
		message("  INVALID in the candidate: its checks failed")
	endif()
	message("")
endfunction()

if (NOT DEFINED BASELINE OR NOT DEFINED CANDIDATE)
	message(FATAL_ERROR "Usage: cmake -DBASELINE=<runs> -DCANDIDATE=<runs> -P CompareResults.cmake")
endif()
foreach(side baseline candidate)
	string(TOUPPER "${side}" variable)
	set(${side}.runs 0)
	foreach(run IN LISTS ${variable})
		math(EXPR ${side}.runs "${${side}.runs} + 1")
		_readResults("${run}" "${side}.${${side}.runs}")
	endforeach()
	if (${side}.runs EQUAL 0)
		message(FATAL_ERROR "No ${variable} run given")
	endif()
	# The environment of a side is the one of its first run; its other runs must share it.
	foreach(field cpu mode buildType allocator processors)
		set(${side}.${field} "${${side}.1.${field}}")
		foreach(run RANGE 1 ${${side}.runs})
			if (NOT "${${side}.${run}.${field}}" STREQUAL "${${side}.${field}}")
				message("WARNING: the ${side} runs differ in ${field}, their durations do not compare")
				break()
			endif()
		endforeach()
	endforeach()
	_combineRuns(${side})
endforeach()

foreach(side baseline candidate)
	string(SUBSTRING "${side}" 0 1 initial)
	string(TOUPPER "${initial}" initial)
	string(SUBSTRING "${side}" 1 -1 rest)
	set(title "${initial}${rest}:")
	if (${side}.runs EQUAL 1)
		string(APPEND title " ")
		if (side STREQUAL "baseline")
			string(APPEND title " ")
		endif()
		message("${title}${${side}.1.environment}")
	else()
		message("${title} ${${side}.runs} runs")
		foreach(run RANGE 1 ${${side}.runs})
			message("  ${${side}.${run}.environment}")
		endforeach()
	endif()
endforeach()
if (NOT baseline.cpu STREQUAL candidate.cpu)
	message("WARNING: the processors differ, the durations do not compare")
endif()
if (NOT baseline.mode STREQUAL candidate.mode OR NOT baseline.buildType STREQUAL candidate.buildType)
	message("WARNING: the modes or the build types differ, the durations do not compare")
endif()
if (NOT baseline.allocator STREQUAL candidate.allocator)
	message("WARNING: the allocators differ, the durations do not compare")
endif()
if (NOT baseline.processors STREQUAL candidate.processors AND NOT baseline.processors STREQUAL "processors unknown"
	AND NOT candidate.processors STREQUAL "processors unknown")
	message("WARNING: the threads ran on different processors, the durations do not compare")
endif()
message("")

set(onlyInBaseline "")
foreach(name IN LISTS baseline.benchmarks)
	if (name IN_LIST candidate.benchmarks)
		_reportBenchmark("${name}")
	else()
		list(APPEND onlyInBaseline "${name}")
	endif()
endforeach()
set(onlyInCandidate "")
foreach(name IN LISTS candidate.benchmarks)
	if (NOT name IN_LIST baseline.benchmarks)
		list(APPEND onlyInCandidate "${name}")
	endif()
endforeach()
if (onlyInBaseline)
	string(REPLACE ";" ", " onlyInBaseline "${onlyInBaseline}")
	message("Only in the baseline: ${onlyInBaseline}")
endif()
if (onlyInCandidate)
	string(REPLACE ";" ", " onlyInCandidate "${onlyInCandidate}")
	message("Only in the candidate: ${onlyInCandidate}")
endif()
