#[[
Copyright (c) 2019 Gouvernement du Québec

SPDX-License-Identifier: LiLiQ-R-1.1
License-Filename: LICENSES/EN/LiLiQ-R11unicode.txt
]]

# Compares the benchmark results of two runs, written by FMTPerformanceTests (JSON schema version 1,
# described in Documentation/PerformanceTesting.md):
#
#   cmake -DBASELINE=<file or folder> -DCANDIDATE=<file or folder> -P Tests/Performance/CompareResults.cmake
#
# A folder stands for every .json file it holds, such as build/release/tests/performance after a run
# of ctest. For each benchmark, the report gives the change of the median duration and of the process
# peak memory in percent, and the allocations and bytes of a typical call before and after. It only
# reports: nothing fails on a change.

cmake_minimum_required(VERSION 3.19)

# Converts a decimal written without exponent, such as "612.345" or "-0.5", into thousandths: math()
# only computes with integers. Anything else, null included, gives an empty result.
function(_toThousandths p_value p_result)
	if (NOT p_value MATCHES "^(-?)([0-9]+)(\\.([0-9]*))?$")
		set(${p_result} "" PARENT_SCOPE)
		return()
	endif()
	set(sign "${CMAKE_MATCH_1}")
	set(integerPart "${CMAKE_MATCH_2}")
	string(SUBSTRING "${CMAKE_MATCH_4}000" 0 3 fraction)
	# Leading zeros are removed, so that no number can be read as octal.
	string(REGEX REPLACE "^0+([0-9])" "\\1" integerPart "${integerPart}")
	string(REGEX REPLACE "^0+([0-9])" "\\1" fraction "${fraction}")
	math(EXPR thousandths "${integerPart} * 1000 + ${fraction}")
	if (sign)
		math(EXPR thousandths "0 - ${thousandths}")
	endif()
	set(${p_result} "${thousandths}" PARENT_SCOPE)
endfunction()

# Writes the change from p_before to p_after in percent, with one decimal, such as "-12.4%".
function(_percentChange p_before p_after p_result)
	_toThousandths("${p_before}" before)
	_toThousandths("${p_after}" after)
	if (before STREQUAL "" OR after STREQUAL "" OR before EQUAL 0)
		set(${p_result} "n/a" PARENT_SCOPE)
		return()
	endif()
	math(EXPR tenths "(${after} - ${before}) * 1000 / ${before}")
	set(sign "+")
	if (tenths LESS 0)
		set(sign "-")
		math(EXPR tenths "0 - ${tenths}")
	endif()
	math(EXPR units "${tenths} / 10")
	math(EXPR decimal "${tenths} % 10")
	set(${p_result} "${sign}${units}.${decimal}%" PARENT_SCOPE)
endfunction()

# Writes a duration read from the results with one decimal: string(JSON) returns it with every
# digit of its binary value, such as 378.11599999999999.
function(_formatDuration p_value p_result)
	_toThousandths("${p_value}" thousandths)
	if (thousandths STREQUAL "" OR thousandths LESS 0)
		set(${p_result} "${p_value}" PARENT_SCOPE)
		return()
	endif()
	math(EXPR units "${thousandths} / 1000")
	math(EXPR tenth "(${thousandths} % 1000) / 100")
	set(${p_result} "${units}.${tenth}" PARENT_SCOPE)
endfunction()

# Reads the results of p_path, a file or a folder, into variables named
# <p_side>.<benchmark>.<field>, the benchmark names into <p_side>.benchmarks and a description of the
# run into <p_side>.environment. The environment is the one of the first file.
function(_readResults p_path p_side)
	if (IS_DIRECTORY "${p_path}")
		file(GLOB files "${p_path}/*.json")
	else()
		set(files "${p_path}")
	endif()
	if (NOT files)
		message(FATAL_ERROR "No results in ${p_path}")
	endif()
	set(benchmarks "")
	foreach(file IN LISTS files)
		file(READ "${file}" json)
		if (NOT DEFINED environment)
			foreach(field commit dirty buildType cpu mode timestamp)
				string(JSON ${field} GET "${json}" environment ${field})
			endforeach()
			# Results written before the allocator was recorded have none.
			string(JSON allocator ERROR_VARIABLE missingAllocator GET "${json}" environment allocator)
			if (missingAllocator)
				set(allocator "allocator unknown")
			endif()
			set(environment "commit ${commit}")
			if (dirty)
				string(APPEND environment " (modified)")
			endif()
			string(APPEND environment ", ${buildType}, ${allocator}, ${cpu}, mode ${mode}, ${timestamp}")
			set("${p_side}.cpu" "${cpu}" PARENT_SCOPE)
			set("${p_side}.mode" "${mode}" PARENT_SCOPE)
			set("${p_side}.buildType" "${buildType}" PARENT_SCOPE)
			set("${p_side}.allocator" "${allocator}" PARENT_SCOPE)
		endif()
		string(JSON count LENGTH "${json}" results)
		if (count GREATER 0)
			math(EXPR last "${count} - 1")
			foreach(index RANGE ${last})
				string(JSON name GET "${json}" results ${index} benchmark)
				foreach(field medianNs allocationsPerCallMedian allocatedBytesPerCallMedian processPeakPrivateBytes valid)
					string(JSON value GET "${json}" results ${index} ${field})
					set("${p_side}.${name}.${field}" "${value}" PARENT_SCOPE)
				endforeach()
				list(APPEND benchmarks "${name}")
			endforeach()
		endif()
	endforeach()
	set("${p_side}.benchmarks" "${benchmarks}" PARENT_SCOPE)
	set("${p_side}.environment" "${environment}" PARENT_SCOPE)
endfunction()

# Prints what changed for one benchmark present in both runs.
function(_reportBenchmark p_name)
	set(before "baseline.${p_name}")
	set(after "candidate.${p_name}")
	_percentChange("${${before}.medianNs}" "${${after}.medianNs}" durationChange)
	_percentChange("${${before}.processPeakPrivateBytes}" "${${after}.processPeakPrivateBytes}" memoryChange)
	_formatDuration("${${before}.medianNs}" durationBefore)
	_formatDuration("${${after}.medianNs}" durationAfter)
	message("${p_name}")
	message("  Median duration:  ${durationChange}  (${durationBefore} ns -> ${durationAfter} ns)")
	message("  Allocations:      ${${before}.allocationsPerCallMedian} -> ${${after}.allocationsPerCallMedian} per call")
	message("  Allocated bytes:  ${${before}.allocatedBytesPerCallMedian} -> ${${after}.allocatedBytesPerCallMedian} per call")
	message("  Peak memory:      ${memoryChange}  (process peak private bytes)")
	if (NOT ${before}.valid)
		message("  INVALID in the baseline: its checks failed")
	endif()
	if (NOT ${after}.valid)
		message("  INVALID in the candidate: its checks failed")
	endif()
	message("")
endfunction()

if (NOT DEFINED BASELINE OR NOT DEFINED CANDIDATE)
	message(FATAL_ERROR "Usage: cmake -DBASELINE=<file or folder> -DCANDIDATE=<file or folder> -P CompareResults.cmake")
endif()
_readResults("${BASELINE}" baseline)
_readResults("${CANDIDATE}" candidate)

message("Baseline:  ${baseline.environment}")
message("Candidate: ${candidate.environment}")
if (NOT baseline.cpu STREQUAL candidate.cpu)
	message("WARNING: the processors differ, the durations do not compare")
endif()
if (NOT baseline.mode STREQUAL candidate.mode OR NOT baseline.buildType STREQUAL candidate.buildType)
	message("WARNING: the modes or the build types differ, the durations do not compare")
endif()
if (NOT baseline.allocator STREQUAL candidate.allocator)
	message("WARNING: the allocators differ, the durations do not compare")
endif()
message("")

set(onlyInBaseline "")
foreach(name IN LISTS baseline.benchmarks)
	if (name IN_LIST candidate.benchmarks)
		_reportBenchmark("${name}")
	else()
		list(APPEND onlyInBaseline "${name}")
	endif()
endforeach()
set(onlyInCandidate "")
foreach(name IN LISTS candidate.benchmarks)
	if (NOT name IN_LIST baseline.benchmarks)
		list(APPEND onlyInCandidate "${name}")
	endif()
endforeach()
if (onlyInBaseline)
	string(REPLACE ";" ", " onlyInBaseline "${onlyInBaseline}")
	message("Only in the baseline: ${onlyInBaseline}")
endif()
if (onlyInCandidate)
	string(REPLACE ";" ", " onlyInCandidate "${onlyInCandidate}")
	message("Only in the candidate: ${onlyInCandidate}")
endif()
