#[[
Copyright (c) 2019 Gouvernement du Québec

SPDX-License-Identifier: LiLiQ-R-1.1
License-Filename: LICENSES/EN/LiLiQ-R11unicode.txt
]]

# Compares the benchmark results of two runs, written by FMTPerformanceTests (JSON schema versions 1
# to 4, described in Documentation/PerformanceTesting.md):
#
#   cmake -DBASELINE=<file or folder> -DCANDIDATE=<file or folder> -P Tests/Performance/CompareResults.cmake
#
# A folder stands for every .json file it holds, such as build/release/tests/performance after a run
# of ctest. For each benchmark, the report gives the change of the median duration, of each phase and
# of the process peak memory in percent, and the allocations and bytes of a typical call before and
# after. It warns when the files of a dataset differ. It only reports: nothing fails on a change.

cmake_minimum_required(VERSION 3.19)

include("${CMAKE_CURRENT_LIST_DIR}/ResultsFormat.cmake")

# Reads the results of p_path, a file or a folder, into variables named
# <p_side>.<benchmark>.<field>, the benchmark names into <p_side>.benchmarks and a description of the
# run into <p_side>.environment. The environment is the one of the first file.
function(_readResults p_path p_side)
	if (IS_DIRECTORY "${p_path}")
		file(GLOB files "${p_path}/*.json")
	else()
		set(files "${p_path}")
	endif()
	if (NOT files)
		message(FATAL_ERROR "No results in ${p_path}")
	endif()
	set(benchmarks "")
	foreach(file IN LISTS files)
		file(READ "${file}" json)
		if (NOT DEFINED environment)
			foreach(field commit dirty buildType cpu mode timestamp)
				string(JSON ${field} GET "${json}" environment ${field})
			endforeach()
			# Results written before the allocator was recorded have none.
			string(JSON allocator ERROR_VARIABLE missingAllocator GET "${json}" environment allocator)
			if (missingAllocator)
				set(allocator "allocator unknown")
			endif()
			# Nor the processors their measuring thread ran on.
			string(JSON processors ERROR_VARIABLE missingProcessors GET "${json}" environment processors)
			if (missingProcessors)
				set(processors "processors unknown")
			endif()
			set(environment "commit ${commit}")
			if (dirty)
				string(APPEND environment " (modified)")
			endif()
			string(APPEND environment ", ${buildType}, ${allocator}, ${cpu} (${processors}), mode ${mode}, ${timestamp}")
			set("${p_side}.cpu" "${cpu}" PARENT_SCOPE)
			set("${p_side}.mode" "${mode}" PARENT_SCOPE)
			set("${p_side}.buildType" "${buildType}" PARENT_SCOPE)
			set("${p_side}.allocator" "${allocator}" PARENT_SCOPE)
			set("${p_side}.processors" "${processors}" PARENT_SCOPE)
		endif()
		string(JSON count LENGTH "${json}" results)
		if (count GREATER 0)
			math(EXPR last "${count} - 1")
			foreach(index RANGE ${last})
				string(JSON name GET "${json}" results ${index} benchmark)
				foreach(field medianNs allocationsPerCallMedian allocatedBytesPerCallMedian processPeakPrivateBytes valid)
					string(JSON value GET "${json}" results ${index} ${field})
					set("${p_side}.${name}.${field}" "${value}" PARENT_SCOPE)
				endforeach()
				# Schema 1 results do not record the memory a call keeps.
				string(JSON value ERROR_VARIABLE missingField GET "${json}" results ${index} retainedBytesPerCallMedian)
				if (missingField)
					set(value "n/a")
				endif()
				set("${p_side}.${name}.retainedBytesPerCallMedian" "${value}" PARENT_SCOPE)
				# Schema 3 adds the fingerprint of the dataset and the phases of a call.
				string(JSON value ERROR_VARIABLE missingField GET "${json}" results ${index} datasetFingerprint)
				if (missingField)
					set(value "")
				endif()
				set("${p_side}.${name}.datasetFingerprint" "${value}" PARENT_SCOPE)
				set(phaseNames "")
				string(JSON phaseCount ERROR_VARIABLE missingField LENGTH "${json}" results ${index} phases)
				if (NOT missingField AND phaseCount GREATER 0)
					math(EXPR lastPhase "${phaseCount} - 1")
					foreach(phaseIndex RANGE ${lastPhase})
						string(JSON phaseName GET "${json}" results ${index} phases ${phaseIndex} name)
						string(JSON phaseMedian GET "${json}" results ${index} phases ${phaseIndex} medianNs)
						list(APPEND phaseNames "${phaseName}")
						set("${p_side}.${name}.phase.${phaseName}" "${phaseMedian}" PARENT_SCOPE)
					endforeach()
				endif()
				set("${p_side}.${name}.phases" "${phaseNames}" PARENT_SCOPE)
				list(APPEND benchmarks "${name}")
			endforeach()
		endif()
	endforeach()
	set("${p_side}.benchmarks" "${benchmarks}" PARENT_SCOPE)
	set("${p_side}.environment" "${environment}" PARENT_SCOPE)
endfunction()

# Prints what changed for one benchmark present in both runs.
function(_reportBenchmark p_name)
	set(before "baseline.${p_name}")
	set(after "candidate.${p_name}")
	_percentChange("${${before}.medianNs}" "${${after}.medianNs}" durationChange)
	_percentChange("${${before}.processPeakPrivateBytes}" "${${after}.processPeakPrivateBytes}" memoryChange)
	_formatDuration("${${before}.medianNs}" durationBefore)
	_formatDuration("${${after}.medianNs}" durationAfter)
	message("${p_name}")
	if (NOT "${${before}.datasetFingerprint}" STREQUAL "" AND NOT "${${after}.datasetFingerprint}" STREQUAL ""
		AND NOT "${${before}.datasetFingerprint}" STREQUAL "${${after}.datasetFingerprint}")
		message("  WARNING: the files of the dataset differ, the results do not compare")
	endif()
	message("  Median duration:  ${durationChange}  (${durationBefore} -> ${durationAfter})")
	foreach(phase IN LISTS ${after}.phases)
		if (phase IN_LIST ${before}.phases)
			_percentChange("${${before}.phase.${phase}}" "${${after}.phase.${phase}}" phaseChange)
			_formatDuration("${${before}.phase.${phase}}" phaseBefore)
			_formatDuration("${${after}.phase.${phase}}" phaseAfter)
			message("    ${phase}:  ${phaseChange}  (${phaseBefore} -> ${phaseAfter})")
		endif()
	endforeach()
	message("  Allocations:      ${${before}.allocationsPerCallMedian} -> ${${after}.allocationsPerCallMedian} per call")
	message("  Allocated bytes:  ${${before}.allocatedBytesPerCallMedian} -> ${${after}.allocatedBytesPerCallMedian} per call")
	message("  Retained bytes:   ${${before}.retainedBytesPerCallMedian} -> ${${after}.retainedBytesPerCallMedian} per call")
	message("  Peak memory:      ${memoryChange}  (process peak private bytes)")
	if (NOT ${before}.valid)
		message("  INVALID in the baseline: its checks failed")
	endif()
	if (NOT ${after}.valid)
		message("  INVALID in the candidate: its checks failed")
	endif()
	message("")
endfunction()

if (NOT DEFINED BASELINE OR NOT DEFINED CANDIDATE)
	message(FATAL_ERROR "Usage: cmake -DBASELINE=<file or folder> -DCANDIDATE=<file or folder> -P CompareResults.cmake")
endif()
_readResults("${BASELINE}" baseline)
_readResults("${CANDIDATE}" candidate)

message("Baseline:  ${baseline.environment}")
message("Candidate: ${candidate.environment}")
if (NOT baseline.cpu STREQUAL candidate.cpu)
	message("WARNING: the processors differ, the durations do not compare")
endif()
if (NOT baseline.mode STREQUAL candidate.mode OR NOT baseline.buildType STREQUAL candidate.buildType)
	message("WARNING: the modes or the build types differ, the durations do not compare")
endif()
if (NOT baseline.allocator STREQUAL candidate.allocator)
	message("WARNING: the allocators differ, the durations do not compare")
endif()
if (NOT baseline.processors STREQUAL candidate.processors AND NOT baseline.processors STREQUAL "processors unknown"
	AND NOT candidate.processors STREQUAL "processors unknown")
	message("WARNING: the threads ran on different processors, the durations do not compare")
endif()
message("")

set(onlyInBaseline "")
foreach(name IN LISTS baseline.benchmarks)
	if (name IN_LIST candidate.benchmarks)
		_reportBenchmark("${name}")
	else()
		list(APPEND onlyInBaseline "${name}")
	endif()
endforeach()
set(onlyInCandidate "")
foreach(name IN LISTS candidate.benchmarks)
	if (NOT name IN_LIST baseline.benchmarks)
		list(APPEND onlyInCandidate "${name}")
	endif()
endforeach()
if (onlyInBaseline)
	string(REPLACE ";" ", " onlyInBaseline "${onlyInBaseline}")
	message("Only in the baseline: ${onlyInBaseline}")
endif()
if (onlyInCandidate)
	string(REPLACE ";" ", " onlyInCandidate "${onlyInCandidate}")
	message("Only in the candidate: ${onlyInCandidate}")
endif()
