#[[
Copyright (c) 2019 Gouvernement du Québec

SPDX-License-Identifier: LiLiQ-R-1.1
License-Filename: LICENSES/EN/LiLiQ-R11unicode.txt
]]

# Reports how benchmarks scale with the number of threads they run on, from results written by
# FMTPerformanceTests (JSON schema version 4, described in Documentation/PerformanceTesting.md):
#
#   cmake -DRESULTS=<file or folder> -P Tests/Performance/ScalingReport.cmake
#
# A folder stands for every .json file it holds, such as build/release/tests/performance after a run
# of ctest. Benchmarks whose names differ only by a ".Threads<N>" part form a family, such as
# Flow.Replanning.Threads1 to Flow.Replanning.Threads10. For each family, from the fewest threads to
# the most, the report gives the median duration of a call and of each phase, the speedup and the
# efficiency against the fewest threads, and the peak private memory of the process with its growth
# per added thread. It warns when the members of a family wrote different results, and only names a
# family of one benchmark, which has nothing to compare. It only reports: nothing fails.

cmake_minimum_required(VERSION 3.19)

include("${CMAKE_CURRENT_LIST_DIR}/ResultsFormat.cmake")

# Writes p_numerator / p_denominator with two decimals, such as "3.47".
function(_ratio p_numerator p_denominator p_result)
	if (p_numerator STREQUAL "" OR p_denominator STREQUAL "" OR p_denominator EQUAL 0)
		set(${p_result} "n/a" PARENT_SCOPE)
		return()
	endif()
	math(EXPR hundredths "${p_numerator} * 100 / ${p_denominator}")
	math(EXPR units "${hundredths} / 100")
	math(EXPR fraction "${hundredths} % 100")
	if (fraction LESS 10)
		set(fraction "0${fraction}")
	endif()
	set(${p_result} "${units}.${fraction}" PARENT_SCOPE)
endfunction()

# Writes a number of bytes in megabytes of 10^6 bytes, as the console of the benchmarks does, with
# one decimal, such as "105.2 MB" or "-0.4 MB".
function(_megabytes p_bytes p_result)
	set(sign "")
	set(bytes "${p_bytes}")
	if (bytes LESS 0)
		set(sign "-")
		math(EXPR bytes "0 - ${bytes}")
	endif()
	math(EXPR tenths "(${bytes} + 50000) / 100000")
	math(EXPR units "${tenths} / 10")
	math(EXPR decimal "${tenths} % 10")
	set(${p_result} "${sign}${units}.${decimal} MB" PARENT_SCOPE)
endfunction()

# Pads p_text with spaces on its right to p_width characters.
function(_pad p_text p_width p_result)
	set(text "${p_text}")
	string(LENGTH "${text}" length)
	while (length LESS p_width)
		string(APPEND text " ")
		math(EXPR length "${length} + 1")
	endwhile()
	set(${p_result} "${text}" PARENT_SCOPE)
endfunction()

if (NOT DEFINED RESULTS)
	message(FATAL_ERROR "Usage: cmake -DRESULTS=<file or folder> -P ScalingReport.cmake")
endif()
if (IS_DIRECTORY "${RESULTS}")
	file(GLOB files "${RESULTS}/*.json")
else()
	set(files "${RESULTS}")
endif()
if (NOT files)
	message(FATAL_ERROR "No results in ${RESULTS}")
endif()

# For a family: <family>.members holds the numbers of threads of its benchmarks, and
# <family>.<threads>.<field> the median, peak, fingerprint and phases of each.
set(families "")
foreach(file IN LISTS files)
	file(READ "${file}" json)
	string(JSON count LENGTH "${json}" results)
	if (count EQUAL 0)
		continue()
	endif()
	math(EXPR last "${count} - 1")
	foreach(index RANGE ${last})
		string(JSON name GET "${json}" results ${index} benchmark)
		if (NOT name MATCHES "\\.Threads[0-9]+")
			continue()
		endif()
		string(REGEX REPLACE "\\.Threads[0-9]+" "" family "${name}")
		string(JSON threads GET "${json}" results ${index} threads)
		list(APPEND families "${family}")
		list(APPEND "${family}.members" "${threads}")
		string(JSON median GET "${json}" results ${index} medianNs)
		string(JSON peak GET "${json}" results ${index} processPeakPrivateBytes)
		set("${family}.${threads}.name" "${name}")
		set("${family}.${threads}.median" "${median}")
		set("${family}.${threads}.peak" "${peak}")
		# Results written before schema 4 have no fingerprint.
		string(JSON fingerprint ERROR_VARIABLE missingFingerprint GET "${json}" results ${index} resultFingerprint)
		if (missingFingerprint)
			set(fingerprint "")
		endif()
		set("${family}.${threads}.fingerprint" "${fingerprint}")
		set(phases "")
		string(JSON phaseCount ERROR_VARIABLE missingPhases LENGTH "${json}" results ${index} phases)
		if (NOT missingPhases AND phaseCount GREATER 0)
			math(EXPR lastPhase "${phaseCount} - 1")
			foreach(phase RANGE ${lastPhase})
				string(JSON phaseName GET "${json}" results ${index} phases ${phase} name)
				string(JSON phaseMedian GET "${json}" results ${index} phases ${phase} medianNs)
				list(APPEND phases "${phaseName}")
				set("${family}.${threads}.phase.${phaseName}" "${phaseMedian}")
			endforeach()
		endif()
		set("${family}.phases" "${phases}")
	endforeach()
endforeach()
if (NOT families)
	message("No result of ${RESULTS} belongs to a benchmark with a .Threads<N> part in its name.")
	return()
endif()
list(REMOVE_DUPLICATES families)
list(SORT families)

foreach(family IN LISTS families)
	set(members "${${family}.members}")
	list(REMOVE_DUPLICATES members)
	list(SORT members COMPARE NATURAL)
	list(GET members 0 base)
	list(LENGTH members memberCount)
	if (memberCount LESS 2)
		message("")
		message("${family}: only ${${family}.${base}.name}, on ${base} thread(s), nothing to compare")
		continue()
	endif()
	_toThousandths("${${family}.${base}.median}" baseMedian)
	set(basePeak "${${family}.${base}.peak}")
	message("")
	message("${family}, against ${base} thread(s)")
	message("  threads  median            speedup  efficiency  peak memory  per added thread")
	foreach(threads IN LISTS members)
		_toThousandths("${${family}.${threads}.median}" median)
		_formatDuration("${${family}.${threads}.median}" medianText)
		_ratio("${baseMedian}" "${median}" speedup)
		if (median STREQUAL "" OR median EQUAL 0 OR baseMedian STREQUAL "")
			set(efficiency "n/a")
		else()
			math(EXPR percent "${baseMedian} * ${base} * 100 / (${median} * ${threads})")
			set(efficiency "${percent}%")
		endif()
		_megabytes("${${family}.${threads}.peak}" peakText)
		set(growth "")
		if (NOT threads EQUAL base)
			math(EXPR growthBytes "(${${family}.${threads}.peak} - ${basePeak}) / (${threads} - ${base})")
			_megabytes("${growthBytes}" growth)
		endif()
		_pad("  ${threads}" 11 column1)
		_pad("${medianText}" 18 column2)
		_pad("${speedup}" 9 column3)
		_pad("${efficiency}" 12 column4)
		_pad("${peakText}" 13 column5)
		message("${column1}${column2}${column3}${column4}${column5}${growth}")
		foreach(phase IN LISTS "${family}.phases")
			if (NOT DEFINED "${family}.${threads}.phase.${phase}")
				continue()
			endif()
			_toThousandths("${${family}.${threads}.phase.${phase}}" phaseMedian)
			_toThousandths("${${family}.${base}.phase.${phase}}" basePhaseMedian)
			_formatDuration("${${family}.${threads}.phase.${phase}}" phaseText)
			_ratio("${basePhaseMedian}" "${phaseMedian}" phaseSpeedup)
			message("           ${phase}: ${phaseText}, speedup ${phaseSpeedup}")
		endforeach()
	endforeach()
	set(fingerprints "")
	foreach(threads IN LISTS members)
		if (NOT "${${family}.${threads}.fingerprint}" STREQUAL "")
			list(APPEND fingerprints "${${family}.${threads}.fingerprint}")
		endif()
	endforeach()
	list(REMOVE_DUPLICATES fingerprints)
	list(LENGTH fingerprints distinct)
	if (distinct GREATER 1)
		message(WARNING "${family}: its members wrote different results (${fingerprints})")
	elseif (distinct EQUAL 1)
		message("  every member wrote the same results (${fingerprints})")
	endif()
endforeach()
