test_that("Version information is consistent", {
  version <- new(FMTversion)
  major <- version$getmajor()
  minor <- version$getminor()
  patch <- version$getpatch()
  versionString <- version$getversion()
  expect_gte(major, 0L)
  expect_gte(minor, 0L)
  expect_gte(patch, 0L)
  expect_true(nzchar(versionString))
  expect_true(version$isatleast(major, minor, patch))
  expect_true(nzchar(version$getlicense(FALSE)))
  expect_true(nzchar(version$getchangelog(FALSE)))
})
