#[[
Copyright (c) 2019 Gouvernement du Québec

SPDX-License-Identifier: LiLiQ-R-1.1
License-Filename: LICENSES/EN/LiLiQ-R11unicode.txt
]]

#[[
Prints the summary of a test pass: a table by level, then the failed and the skipped tests with
their reason. Run in script mode, right after ctest:

    cmake -DTEST_RESULTS=<file> -DTEST_LIST=<file> -P Tests/Support/TestSummary.cmake

TEST_RESULTS is the file written by ctest --output-junit. TEST_LIST is the output of
ctest --show-only=json-v1 with the same filter, which gives the labels of each test. The level of a
test is its label unit, integration, system or performance; a test without one, such as a fixture,
counts under other.

The counts are those of ctest. Its final line counts a skipped test as passed, a test that could not
run (Not Run) as failed, and leaves the disabled tests out of its total: there, passed is
Passed + Skipped, and the total is Total - Disabled. In the results of ctest 3.31, a test that could
not run is written like a skipped one (status notrun, element skipped); only a message that starts
with SKIP_ tells a test that skipped itself.

The script never fails because of a test: the caller decides what a failure means.

The test outputs in the results hold ;, [ ] and XML entities. The file is therefore cut with
string(FIND) and string(SUBSTRING), never turned into a CMake list, and a name only enters a list
once its ; [ ] are escaped.
]]

cmake_minimum_required(VERSION 3.19)

set(_summaryLevels unit integration system performance)

# Replaces the XML entities of p_text, including those that _summaryListItem adds.
function(_summaryDecode p_out p_text)
    string(REPLACE "&lt;" "<" p_text "${p_text}")
    string(REPLACE "&gt;" ">" p_text "${p_text}")
    string(REPLACE "&quot;" "\"" p_text "${p_text}")
    string(REPLACE "&apos;" "'" p_text "${p_text}")
    string(REPLACE "&#9;" "\t" p_text "${p_text}")
    string(REPLACE "&#10;" "\n" p_text "${p_text}")
    string(REPLACE "&#13;" "" p_text "${p_text}")
    string(REPLACE "&#59;" ";" p_text "${p_text}")
    string(REPLACE "&#91;" "[" p_text "${p_text}")
    string(REPLACE "&#93;" "]" p_text "${p_text}")
    string(REPLACE "&amp;" "&" p_text "${p_text}")
    set(${p_out} "${p_text}" PARENT_SCOPE)
endfunction()

# Escapes the characters that would split or nest a list item. p_text is still XML encoded.
function(_summaryListItem p_out p_text)
    string(REPLACE ";" "&#59;" p_text "${p_text}")
    string(REPLACE "[" "&#91;" p_text "${p_text}")
    string(REPLACE "]" "&#93;" p_text "${p_text}")
    set(${p_out} "${p_text}" PARENT_SCOPE)
endfunction()

# Formats a duration in seconds, rounded to two decimals as ctest prints it.
function(_summarySeconds p_out p_value)
    set(hundredths 0)
    if(p_value MATCHES "^([0-9]+)(\\.([0-9]*))?$")
        string(SUBSTRING "${CMAKE_MATCH_3}000" 0 3 thousandths)
        math(EXPR hundredths "(${CMAKE_MATCH_1}${thousandths} + 5) / 10")
    endif()
    # Otherwise the time is in scientific notation: well under a hundredth of a second.
    math(EXPR integer "${hundredths} / 100")
    math(EXPR fraction "${hundredths} % 100")
    if(fraction LESS 10)
        set(fraction "0${fraction}")
    endif()
    set(${p_out} "${integer}.${fraction} s" PARENT_SCOPE)
endfunction()

# Pads p_text to p_width, on the left when p_right is TRUE.
function(_summaryPad p_out p_text p_width p_right)
    string(LENGTH "${p_text}" length)
    set(padding "")
    if(length LESS p_width)
        math(EXPR missing "${p_width} - ${length}")
        string(REPEAT " " ${missing} padding)
    endif()
    if(p_right)
        set(${p_out} "${padding}${p_text}" PARENT_SCOPE)
    else()
        set(${p_out} "${p_text}${padding}" PARENT_SCOPE)
    endif()
endfunction()

# Returns the level of a test from its labels, or other.
function(_summaryLevel p_out p_labels)
    set(level "other")
    foreach(candidate IN LISTS _summaryLevels)
        if(candidate IN_LIST p_labels)
            set(level "${candidate}")
            break()
        endif()
    endforeach()
    set(${p_out} "${level}" PARENT_SCOPE)
endfunction()

function(_summaryPrint)
    if(NOT DEFINED TEST_RESULTS OR TEST_RESULTS STREQUAL "")
        message("Test summary: no result file was given (TEST_RESULTS).")
        return()
    endif()

    # The list gives the level of each test.
    set(listedCount -1)
    set(listedNames "")
    if(DEFINED TEST_LIST AND EXISTS "${TEST_LIST}")
        file(READ "${TEST_LIST}" listJson)
        string(JSON tests ERROR_VARIABLE jsonError GET "${listJson}" tests)
        if(jsonError)
            message("Test summary: cannot read the test list ${TEST_LIST}: ${jsonError}")
        else()
            string(JSON listedCount LENGTH "${tests}")
            if(listedCount GREATER 0)
                math(EXPR lastTest "${listedCount} - 1")
                foreach(testIndex RANGE ${lastTest})
                    string(JSON test GET "${tests}" ${testIndex})
                    string(JSON name GET "${test}" name)
                    set(labels "")
                    string(JSON properties ERROR_VARIABLE noProperty GET "${test}" properties)
                    if(NOT noProperty)
                        string(JSON propertyCount LENGTH "${properties}")
                        if(propertyCount GREATER 0)
                            math(EXPR lastProperty "${propertyCount} - 1")
                            foreach(propertyIndex RANGE ${lastProperty})
                                string(JSON propertyName GET "${properties}" ${propertyIndex} name)
                                if(propertyName STREQUAL "LABELS")
                                    string(JSON labelCount LENGTH "${properties}" ${propertyIndex} value)
                                    if(labelCount GREATER 0)
                                        math(EXPR lastLabel "${labelCount} - 1")
                                        foreach(labelIndex RANGE ${lastLabel})
                                            string(JSON label GET "${properties}" ${propertyIndex} value ${labelIndex})
                                            list(APPEND labels "${label}")
                                        endforeach()
                                    endif()
                                endif()
                            endforeach()
                        endif()
                    endif()
                    _summaryLevel(level "${labels}")
                    string(MD5 key "${name}")
                    set(level_${key} "${level}")
                    set(listed_${key} TRUE)
                endforeach()
            endif()
        endif()
    endif()

    if(listedCount EQUAL 0)
        message("Test summary: no test matches this selection.")
        return()
    endif()

    if(NOT EXISTS "${TEST_RESULTS}")
        message("Test summary: no result file ${TEST_RESULTS}.")
        return()
    endif()
    file(READ "${TEST_RESULTS}" rest)
    if(rest STREQUAL "")
        message("Test summary: the result file ${TEST_RESULTS} is empty.")
        return()
    endif()

    foreach(level IN LISTS _summaryLevels ITEMS other)
        foreach(column passed failed skipped disabled total)
            set(count_${level}_${column} 0)
        endforeach()
    endforeach()
    set(failedItems "")
    set(skippedItems "")
    set(resultCount 0)
    set(unlistedResults 0)

    while(TRUE)
        string(FIND "${rest}" "<testcase " start)
        if(start EQUAL -1)
            break()
        endif()
        string(FIND "${rest}" "</testcase>" end)
        if(end LESS start)
            string(SUBSTRING "${rest}" ${start} -1 testCase)
            set(rest "")
        else()
            math(EXPR length "${end} - ${start}")
            string(SUBSTRING "${rest}" ${start} ${length} testCase)
            math(EXPR afterEnd "${end} + 11")
            string(SUBSTRING "${rest}" ${afterEnd} -1 rest)
        endif()
        math(EXPR resultCount "${resultCount} + 1")

        string(FIND "${testCase}" ">" headerEnd)
        string(SUBSTRING "${testCase}" 0 ${headerEnd} header)
        string(REGEX MATCH " name=\"([^\"]*)\"" ignored "${header}")
        set(encodedName "${CMAKE_MATCH_1}")
        _summaryDecode(name "${encodedName}")
        string(REGEX MATCH " time=\"([^\"]*)\"" ignored "${header}")
        _summarySeconds(seconds "${CMAKE_MATCH_1}")
        string(REGEX MATCH " status=\"([^\"]*)\"" ignored "${header}")
        set(status "${CMAKE_MATCH_1}")

        string(MD5 key "${name}")
        if(DEFINED level_${key})
            set(level "${level_${key}}")
        else()
            # Not in the list: the labels that ctest wrote in the results.
            math(EXPR unlistedResults "${unlistedResults} + 1")
            set(labels "")
            if(testCase MATCHES "<property name=\"cmake_labels\" value=\"([^\"]*)\"")
                set(labels "${CMAKE_MATCH_1}")
            endif()
            _summaryLevel(level "${labels}")
        endif()

        set(message "")
        if(testCase MATCHES "<(failure|skipped) message=\"([^\"]*)\"")
            _summaryDecode(message "${CMAKE_MATCH_2}")
        endif()

        _summaryListItem(item "${encodedName}")
        if(status STREQUAL "run")
            set(column passed)
        elseif(status STREQUAL "disabled")
            set(column disabled)
        elseif(status STREQUAL "notrun" AND message MATCHES "^SKIP_")
            # SKIP_RETURN_CODE or SKIP_REGULAR_EXPRESSION: the test chose to skip itself.
            set(column skipped)
            set(reason "")
            string(FIND "${testCase}" "<system-out>" outputStart)
            if(NOT outputStart EQUAL -1)
                string(SUBSTRING "${testCase}" ${outputStart} -1 output)
                string(FIND "${output}" "SKIPPED: " skipStart)
                if(NOT skipStart EQUAL -1)
                    math(EXPR skipStart "${skipStart} + 9")
                    string(SUBSTRING "${output}" ${skipStart} -1 reason)
                    string(REPLACE "&#13;" "\n" reason "${reason}")
                    string(REPLACE "\r" "\n" reason "${reason}")
                    string(REPLACE "</system-out>" "\n" reason "${reason}")
                    string(FIND "${reason}" "\n" lineEnd)
                    if(NOT lineEnd EQUAL -1)
                        string(SUBSTRING "${reason}" 0 ${lineEnd} reason)
                    endif()
                    _summaryDecode(reason "${reason}")
                    string(STRIP "${reason}" reason)
                endif()
            endif()
            list(APPEND skippedItems "${item}")
            set(reason_${key} "${reason}")
            set(seconds_${key} "${seconds}")
        else()
            # A failure, or a test that could not run, which ctest counts as a failure.
            set(column failed)
            set(reason "")
            if(status STREQUAL "notrun")
                set(reason "Not Run")
                if(NOT message STREQUAL "")
                    set(reason "Not Run, ${message}")
                endif()
            elseif(NOT message STREQUAL "" AND NOT message STREQUAL "Failed")
                set(reason "${message}")
            endif()
            list(APPEND failedItems "${item}")
            set(reason_${key} "${reason}")
            set(seconds_${key} "${seconds}")
        endif()
        math(EXPR count_${level}_${column} "${count_${level}_${column}} + 1")
        math(EXPR count_${level}_total "${count_${level}_total} + 1")
    endwhile()

    if(resultCount EQUAL 0)
        message("Test summary: no test result in ${TEST_RESULTS}.")
        return()
    endif()

    # The table: one row per level present, then the total.
    set(columns passed failed skipped disabled total)
    set(headers Passed Failed Skipped Disabled Total)
    _summaryPad(line "Level" 12 FALSE)
    foreach(header IN LISTS headers)
        string(LENGTH "${header}" width)
        math(EXPR width "${width} + 2")
        _summaryPad(cell "${header}" ${width} TRUE)
        string(APPEND line "${cell}")
    endforeach()
    set(report "\nTest summary\n${line}\n")
    foreach(column IN LISTS columns)
        set(sum_${column} 0)
    endforeach()
    foreach(level IN LISTS _summaryLevels ITEMS other)
        if(count_${level}_total EQUAL 0)
            continue()
        endif()
        _summaryPad(line "${level}" 12 FALSE)
        foreach(column header IN ZIP_LISTS columns headers)
            string(LENGTH "${header}" width)
            math(EXPR width "${width} + 2")
            _summaryPad(cell "${count_${level}_${column}}" ${width} TRUE)
            string(APPEND line "${cell}")
            math(EXPR sum_${column} "${sum_${column}} + ${count_${level}_${column}}")
        endforeach()
        string(APPEND report "${line}\n")
    endforeach()
    _summaryPad(line "Total" 12 FALSE)
    foreach(column header IN ZIP_LISTS columns headers)
        string(LENGTH "${header}" width)
        math(EXPR width "${width} + 2")
        _summaryPad(cell "${sum_${column}}" ${width} TRUE)
        string(APPEND line "${cell}")
    endforeach()
    string(APPEND report "${line}\n")

    # Then the failed and the skipped tests, sorted by name, only when there are some.
    foreach(kind Failed Skipped)
        string(TOLOWER "${kind}" lowerKind)
        set(items "${${lowerKind}Items}")
        if(items STREQUAL "")
            continue()
        endif()
        list(SORT items)
        string(APPEND report "\n${kind}:\n")
        foreach(item IN LISTS items)
            _summaryDecode(name "${item}")
            string(MD5 key "${name}")
            set(line "  ${name} (${seconds_${key}})")
            if(NOT reason_${key} STREQUAL "")
                string(APPEND line ": ${reason_${key}}")
            endif()
            string(APPEND report "${line}\n")
        endforeach()
    endforeach()

    # Tests of the list without a result, such as after an interrupted pass.
    if(listedCount GREATER 0)
        math(EXPR missingResults "${listedCount} - ${resultCount} + ${unlistedResults}")
        if(missingResults GREATER 0)
            string(APPEND report "\n${missingResults} listed tests have no result.\n")
        endif()
    endif()

    message("${report}")
endfunction()

_summaryPrint()
