/*
Copyright (c) 2019 Gouvernement du Québec

SPDX-License-Identifier: LiLiQ-R-1.1
License-Filename: LICENSES/EN/LiLiQ-R11unicode.txt
*/

#ifndef FMTfuturdevelopment_Hm_included
#define FMTfuturdevelopment_Hm_included

#include "FMTDevelopment.h"
#include <boost/serialization/serialization.hpp>
#include <memory>
#include <boost/serialization/export.hpp>

namespace Core
{
	// DocString: FMTFuturDevelopment
	/**
	FMTFuturDevelopment is the child class of FMTDevelopment. It represent the description of a
	futur stand that does not exist in the actual forest and is generated by growth or by transition.
	*/
	class FMTEXPORT FMTFuturDevelopment : public FMTDevelopment
		{
		public:
			// DocString: FMTFuturDevelopment::(FMTFuturDevelopment&& rhs)
			/**
			@brief Move copy constructor
			@param[in] rhs development to swap
			*/
			FMTFuturDevelopment(FMTFuturDevelopment&& rhs);
			// DocString: FMTFuturDevelopment::operator=(FMTFuturDevelopment&& rhs)
			/**
			@brief Move copy assignement
			@param[in] rhs development to swap
			*/
			FMTFuturDevelopment& operator=(FMTFuturDevelopment&& rhs);
			// DocString: FMTFuturDevelopment()
			/**
			Default constructor for FMTFuturDevelopment
			*/
			FMTFuturDevelopment();
			// DocString: ~FMTFuturDevelopment()
			/**
			Default destructor for FMTFuturDevelopment.
			*/
			~FMTFuturDevelopment() = default;
			// DocString: FMTFuturDevelopment(const FMTDevelopment&)
			/**
			FMTDevelopment constructor using a FMTDevelopment.
			*/
			FMTFuturDevelopment(const FMTDevelopment& dev);
			// DocString: FMTFuturDevelopment(const FMTFuturDevelopment&)
			/**
			FMTFuturDevelopment copy constructor.
			*/
			FMTFuturDevelopment(const FMTFuturDevelopment& rhs);
			// DocString: FMTFuturDevelopment::operator==
			/**
			FMTFuturDevelopment equality operator.
			*/
			bool operator == (const FMTFuturDevelopment& rhs) const;
			// DocString: FMTFuturDevelopment::operator=
			/**
			FMTFuturDevelopment copy assignment.
			*/
			FMTFuturDevelopment& operator = (const FMTFuturDevelopment& rhs);
			// DocString: FMTFuturDevelopment::operator=
			/**
			FMTFuturDevelopment copy assignment.
			*/
			std::unique_ptr<FMTDevelopment> Clone() const override;
			// DocString: FMTFuturDevelopment::getArea
			/**
			Return the area of the futur development 0.
			*/
			double getArea() const override;
		private:
			// DocString: FMTFuturDevelopment::serialize
			/**
			Serialize function is for serialization, used to do multiprocessing across multiple cpus (pickle in Pyhton)
			*/
			friend class boost::serialization::access;
			template<class Archive>
			void serialize(Archive& ar, const unsigned int version)
			{
				try {
					ar& boost::serialization::make_nvp("development", boost::serialization::base_object<FMTDevelopment>(*this));
				}
				catch (...)
				{
					_exhandler->printExceptions("", "FMTFuturDevelopment::serialize", __LINE__, __FILE__);
				}
			}

		};
}

BOOST_CLASS_EXPORT_KEY(Core::FMTFuturDevelopment)
#endif // FMTDEV_Hm_included