/*
Copyright (c) 2019 Gouvernement du Québec

SPDX-License-Identifier: LiLiQ-R-1.1
License-Filename: LICENSES/EN/LiLiQ-R11unicode.txt
*/

#ifndef FMTFORK_Hm_included
#define FMTFORK_Hm_included

#include "FMTTransitionMask.h"
#include "FMTBounds.hpp"
#include <vector>
#include <boost/serialization/serialization.hpp>
#include <boost/serialization/split_member.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/export.hpp>
#include <boost/serialization/unique_ptr.hpp>
#include <boost/serialization/vector.hpp>
#include "FMTObject.h"

namespace Core
{

class FMTDevelopment;
class FMTDevelopmentPath;
class FMTYieldRequest;
class FMTYields;
class FMTTheme;
class FMTMaskFilter;


// DocString: FMTFork
/**
@brief Fork of a transition, holding the transition masks (targets and proportions) applied to a development when an action is operated.
*/
class FMTEXPORT FMTFork : public FMTSpec, public FMTObject
    {
    public:
        // DocString: FMTFork()
        /**
        @brief Default constructor for FMTFork.
        */
        FMTFork();
        // DocString: FMTFork(const FMTFork&)
        /**
        @brief Copy constructor for FMTFork.
        @param[in] rhs the FMTFork to copy.
        */
        FMTFork(const FMTFork& rhs)=default;
		// DocString: ~FMTFork()
		/**
		@brief Destructor for FMTFork.
		*/
		~FMTFork();
        // DocString: FMTFork::operator=
        /**
        @brief Copy assignment operator for FMTFork.
        @param[in] rhs the FMTFork to copy.
        @return a reference to this FMTFork.
        */
        FMTFork& operator = (const FMTFork& rhs)=default;
        // DocString: FMTFork::add
        /**
        @brief Add a transition mask to the fork.
        @param[in] transition the transition mask.
        */
        void add(const FMTTransitionMask& transition);
        // DocString: FMTFork::clear
        /**
        @brief Clear the transition masks of the fork.
        */
        void clear();
		// DocString: FMTFork::getPaths
		/**
		@brief Return the development paths generated by the fork on a base development.
		@param[in] base the base development.
		@param[in] ylds the yields.
		@param[in] themes the themes.
		@param[in] reset_age if true resets the age.
		@return the development paths.
		*/
		std::vector<FMTDevelopmentPath> getPaths(const Core::FMTDevelopment& base, const Core::FMTYields& ylds,
				const std::vector<FMTTheme>& themes,const bool& reset_age) const;
        // DocString: FMTFork::getMax
        /**
        @brief Return the development with the maximal proportion generated by the fork on a base development.
        @param[in] base the base development.
        @param[in] ylds the yields.
        @param[in] themes the themes.
        @param[in] reset_age if true resets the age.
        @return the maximal development.
        */
        FMTDevelopment getMax(const FMTDevelopment& base,const FMTYields& ylds,const std::vector<FMTTheme>& themes, const bool& reset_age) const;
		// DocString: FMTFork::getMaskTrans
		/**
		@brief Return the transition masks of the fork.
		@return the transition masks.
		*/
		std::vector<FMTTransitionMask> getMaskTrans() const;
		// DocString: FMTFork::operator==
		/**
		@brief Comparison operator for FMTFork.
		@param[in] rhs the FMTFork to compare to.
		@return true if both forks are equal else false.
		*/
		bool operator == (const FMTFork& rhs) const;
        // DocString: FMTFork::single
        /**
        @brief Return a fork keeping only a single transition mask.
        @return the single fork.
        */
        FMTFork single() const;
        // DocString: FMTFork::sumProp
        /**
        @brief Return the sum of the proportions of the transition masks.
        @return the sum of the proportions.
        */
        double sumProp() const;
        // DocString: FMTFork::size
        /**
        @brief Return the number of transition masks of the fork.
        @return the number of transition masks.
        */
        size_t size() const;
		// DocString: FMTFork::presolve
		/**
		@brief Return a presolved copy of the fork using a mask filter and the presolved themes.
		@param[in] filter the mask filter.
		@param[in] presolvedthemes the presolved themes.
		@return the presolved fork.
		*/
		FMTFork presolve(const FMTMaskFilter& filter, const std::vector<FMTTheme>&presolvedthemes) const;
        // DocString: FMTFork::presolveRef
        /**
        @brief Presolve the fork in place using a mask filter and the presolved themes.
        @param[in] filter the mask filter.
        @param[in] presolvedthemes the presolved themes.
        */
        void presolveRef(const FMTMaskFilter& filter, const std::vector<FMTTheme>& presolvedthemes);
        // DocString: FMTFork::operator std::string
        /**
        @brief Return the string representation of the fork.
        @return the string representation.
        */
        operator std::string() const override;
    private:
        friend class boost::serialization::access;
        // DocString: FMTFork::serialize
        /**
        @brief Serialize the FMTFork for multiprocessing across multiple cpus (pickle in Python).
        @tparam Archive the archive type.
        @param[in,out] ar the archive to serialize to or from.
        @param[in] version the serialization version.
        */
        template<class Archive>
        void serialize(Archive& ar, const unsigned int version)
        {
            ar& boost::serialization::make_nvp("specifications", boost::serialization::base_object<FMTSpec>(*this));
            ar& m_transitions;
        }
        std::vector<FMTTransitionMask>m_transitions;
        // DocString: FMTFork::_getPath
        /**
        @brief Return the development path generated by a single transition mask on a base development.
        @param[in] p_target the transition mask.
        @param[in] p_base the base development.
        @param[in] p_yields the yields.
        @param[in] p_themes the themes.
        @param[in] p_AgeReset if true resets the age.
        @return the development path.
        */
        FMTDevelopmentPath _getPath(const FMTTransitionMask& p_target,
            const Core::FMTDevelopment& p_base, const Core::FMTYields& p_yields,
            const std::vector<FMTTheme>& p_themes, bool p_AgeReset) const;
    };

}

BOOST_CLASS_EXPORT_KEY(Core::FMTFork)

#endif // FMTFORK_Hm_included
