/*
Copyright (c) 2019 Gouvernement du Québec

SPDX-License-Identifier: LiLiQ-R-1.1
License-Filename: LICENSES/EN/LiLiQ-R11unicode.txt
*/

#ifndef FMTfuturdevelopment_Hm_included
#define FMTfuturdevelopment_Hm_included

#include "FMTDevelopment.h"
#include <boost/serialization/serialization.hpp>
#include <memory>
#include <boost/serialization/export.hpp>

namespace Core
{
	// DocString: FMTFuturDevelopment
	/**
	@brief Child class of FMTDevelopment representing a future stand generated by growth or transition, not existing in the actual forest.
	*/
	class FMTEXPORT FMTFuturDevelopment : public FMTDevelopment
		{
		public:
			// DocString: FMTFuturDevelopment::(FMTFuturDevelopment&& rhs)
			/**
			@brief Move copy constructor
			@param[in] rhs development to swap
			*/
			FMTFuturDevelopment(FMTFuturDevelopment&& rhs);
			// DocString: FMTFuturDevelopment::operator=(FMTFuturDevelopment&& rhs)
			/**
			@brief Move assignment operator for FMTFuturDevelopment.
			@param[in] rhs the development to move from.
			@return a reference to this FMTFuturDevelopment.
			*/
			FMTFuturDevelopment& operator=(FMTFuturDevelopment&& rhs);
			// DocString: FMTFuturDevelopment()
			/**
			@brief Default constructor for FMTFuturDevelopment.
			*/
			FMTFuturDevelopment();
			// DocString: ~FMTFuturDevelopment()
			/**
			@brief Default destructor for FMTFuturDevelopment.
			*/
			~FMTFuturDevelopment() = default;
			// DocString: FMTFuturDevelopment(const FMTDevelopment&)
			/**
			@brief Construct a future development from a development.
			@param[in] dev the development.
			*/
			FMTFuturDevelopment(const FMTDevelopment& dev);
			// DocString: FMTFuturDevelopment(const FMTFuturDevelopment&)
			/**
			@brief Copy constructor for FMTFuturDevelopment.
			@param[in] rhs the FMTFuturDevelopment to copy.
			*/
			FMTFuturDevelopment(const FMTFuturDevelopment& rhs);
			// DocString: FMTFuturDevelopment::operator==
			/**
			@brief Equality comparison operator of FMTFuturDevelopment.
			@param[in] rhs the development to compare with.
			@return true if both developments are equal else false.
			*/
			bool operator == (const FMTFuturDevelopment& rhs) const;
			// DocString: FMTFuturDevelopment::operator=
			/**
			@brief Copy assignment operator for FMTFuturDevelopment.
			@param[in] rhs the FMTFuturDevelopment to copy.
			@return a reference to this FMTFuturDevelopment.
			*/
			FMTFuturDevelopment& operator = (const FMTFuturDevelopment& rhs);
			// DocString: FMTFuturDevelopment::operator=
			/**
			@brief Return a unique pointer of FMTDevelopment cloning the future development.
			@return a unique pointer to the cloned development.
			*/
			std::unique_ptr<FMTDevelopment> clone() const override;
			// DocString: FMTFuturDevelopment::getArea
			/**
			@brief Return the area of the future development, which is 0.
			@return the area of the future development (0).
			*/
			double getArea() const override;
		private:
			// DocString: FMTFuturDevelopment::serialize
			/**
			@brief Serialize the FMTFuturDevelopment through its base FMTDevelopment for multiprocessing across multiple cpus (pickle in Python).
			@tparam Archive the archive type.
			@param[in,out] ar the archive to serialize to or from.
			@param[in] version the serialization version.
			*/
			friend class boost::serialization::access;
			template<class Archive>
			void serialize(Archive& ar, const unsigned int version)
			{
				try {
					ar& boost::serialization::make_nvp("development", boost::serialization::base_object<FMTDevelopment>(*this));
				}
				catch (...)
				{
					_exhandler->printExceptions("", "FMTFuturDevelopment::serialize", __LINE__, __FILE__);
				}
			}

		};
}

BOOST_CLASS_EXPORT_KEY(Core::FMTFuturDevelopment)
#endif // FMTDEV_Hm_included