/*
Copyright (c) 2019 Gouvernement du Québec

SPDX-License-Identifier: LiLiQ-R-1.1
License-Filename: LICENSES/EN/LiLiQ-R11unicode.txt
*/

#ifndef FMTfuturdevelopment_Hm_included
#define FMTfuturdevelopment_Hm_included

#include "FMTdevelopment.h"
#include <boost/serialization/serialization.hpp>
#include <memory>
#include <boost/serialization/export.hpp>

namespace Core
{
	// DocString: FMTfuturdevelopment
	/**
	FMTfuturdevelopment is the child class of FMTdevelopment. It represent the description of a
	futur stand that does not exist in the actual forest and is generated by growth or by transition.
	*/
	class FMTEXPORT FMTfuturdevelopment : public FMTdevelopment
		{
		public:
			// DocString: FMTfuturdevelopment::(FMTfuturdevelopment&& rhs)
			/**
			@brief Move copy constructor
			@param[in] rhs development to swap
			*/
			FMTfuturdevelopment(FMTfuturdevelopment&& rhs);
			// DocString: FMTfuturdevelopment::operator=(FMTfuturdevelopment&& rhs)
			/**
			@brief Move copy assignement
			@param[in] rhs development to swap
			*/
			FMTfuturdevelopment& operator=(FMTfuturdevelopment&& rhs);
			// DocString: FMTfuturdevelopment()
			/**
			Default constructor for FMTfuturdevelopment
			*/
			FMTfuturdevelopment();
			// DocString: ~FMTfuturdevelopment()
			/**
			Default destructor for FMTfuturdevelopment.
			*/
			~FMTfuturdevelopment() = default;
			// DocString: FMTfuturdevelopment(const FMTdevelopment&)
			/**
			FMTdevelopment constructor using a FMTdevelopment.
			*/
			FMTfuturdevelopment(const FMTdevelopment& dev);
			// DocString: FMTfuturdevelopment(const FMTfuturdevelopment&)
			/**
			FMTfuturdevelopment copy constructor.
			*/
			FMTfuturdevelopment(const FMTfuturdevelopment& rhs);
			// DocString: FMTfuturdevelopment::operator==
			/**
			FMTfuturdevelopment equality operator.
			*/
			bool operator == (const FMTfuturdevelopment& rhs) const;
			// DocString: FMTfuturdevelopment::operator=
			/**
			FMTfuturdevelopment copy assignment.
			*/
			FMTfuturdevelopment& operator = (const FMTfuturdevelopment& rhs);
			// DocString: FMTfuturdevelopment::operator=
			/**
			FMTfuturdevelopment copy assignment.
			*/
			std::unique_ptr<FMTdevelopment> Clone() const override;
			// DocString: FMTfuturdevelopment::getarea
			/**
			Return the area of the futur development 0.
			*/
			double getarea() const override;
		private:
			// DocString: FMTfuturdevelopment::serialize
			/**
			Serialize function is for serialization, used to do multiprocessing across multiple cpus (pickle in Pyhton)
			*/
			friend class boost::serialization::access;
			template<class Archive>
			void serialize(Archive& ar, const unsigned int version)
			{
				try {
					ar& boost::serialization::make_nvp("development", boost::serialization::base_object<FMTdevelopment>(*this));
				}
				catch (...)
				{
					_exhandler->printexceptions("", "FMTfuturdevelopment::serialize", __LINE__, __FILE__);
				}
			}

		};
}

BOOST_CLASS_EXPORT_KEY(Core::FMTfuturdevelopment)
#endif // FMTDEV_Hm_included