set(FMTpackageloc "FMT-${BUILD_TYPE}-${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}-w64-${CMAKE_CXX_COMPILER_ID}-${CMAKE_CXX_COMPILER_VERSION}")
		set(FMTdir "${CMAKE_BINARY_DIR}/${FMTpackageloc}")
		message("Building ${FMTdir}")
		file(MAKE_DIRECTORY "${FMTdir}")
		file(MAKE_DIRECTORY "${FMTdir}/Include")
		set(headers "${FMTHEADERFILES}")
		foreach(headerfile ${headers})
			file(COPY "${headerfile}" DESTINATION "${FMTdir}/Include")
		endforeach()
		set(MSVC "${MSVC}")
		if (MSVC)
			FILE(GLOB FMTlibfiles "${CMAKE_BINARY_DIR}/bin/${BUILD_TYPE}/FMTlib*")
		else()
			FILE(GLOB FMTlibfiles "${CMAKE_BINARY_DIR}/bin/${BUILD_TYPE}/libFMTlib*")
		endif(MSVC)
		set (FMTlibdir "${FMTdir}/lib")
		#Copy data
		if (GDAL_FOUND)
			file(COPY "${CMAKE_BINARY_DIR}/bin/${BUILD_TYPE}/GDAL_DATA" DESTINATION "${FMTlibdir}")
			file(COPY "${CMAKE_BINARY_DIR}/bin/${BUILD_TYPE}/proj" DESTINATION "${FMTlibdir}")
		endif(GDAL_FOUND)
		file(COPY "${CMAKE_BINARY_DIR}/bin/${BUILD_TYPE}/LICENSES" DESTINATION "${FMTlibdir}")
		file(COPY "${CMAKE_BINARY_DIR}/bin/${BUILD_TYPE}/YieldPredModels" DESTINATION "${FMTlibdir}")
		#Copy the lib
		foreach(FMTlibof ${FMTlibfiles})
			file(COPY "${FMTlibof}" DESTINATION "${FMTlibdir}")
		endforeach()
		#Copy the dependencies
		if (DEPENDENCIES)
			#Copy dependencies
			foreach(FMTdep ${DEPENDENCIES})
				file(COPY "${FMTdep}" DESTINATION "${FMTlibdir}")
			endforeach()
		endif(DEPENDENCIES)
		#Compress the C++ lib
		message("Compressing ${FMTdir}")
		FIND_PROGRAM(ZIP_EXECUTABLE 7z PATHS "C:/Program Files/7-Zip/")
		IF(ZIP_EXECUTABLE)
			execute_process(
				COMMAND "$\{ZIP_EXECUTABLE}" a -t7z "${FMTpackageloc}.7z" "${FMTpackageloc}"
				WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
				)
		ENDIF(ZIP_EXECUTABLE)
		set(PYTHON_FOUND "${PYTHONNAMING}")
		if (DEFINED PYTHON_FOUND)
			file(COPY "${CMAKE_BINARY_DIR}/bin/${BUILD_TYPE}/${wheelname}" DESTINATION "${CMAKE_BINARY_DIR}")
			message("Python package is here ${CMAKE_BINARY_DIR}/${wheelname}")
		endif(DEFINED PYTHON_FOUND)
		set(R_FOUND "${R_FOUND}")
		if (R_FOUND)
			file(COPY "${CMAKE_BINARY_DIR}/bin/${BUILD_TYPE}/${R_package}" DESTINATION "${CMAKE_BINARY_DIR}")
			message("R package is here ${CMAKE_BINARY_DIR}/${R_package}")
		endif(R_FOUND)
		
		message("Release done")
